// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxTjn1eqGHR7-1qhdlJKjm5oGKwasnHD0',
    appId: '1:1059648731028:web:179acc5e16d8a378f58181',
    messagingSenderId: '1059648731028',
    projectId: 'new-pyramidion',
    authDomain: 'new-pyramidion.firebaseapp.com',
    storageBucket: 'new-pyramidion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSzzzR8Er4LkVw6hhfxQ5p8zjbbRtcqCE',
    appId: '1:1059648731028:android:6e67c3015a80c574f58181',
    messagingSenderId: '1059648731028',
    projectId: 'new-pyramidion',
    storageBucket: 'new-pyramidion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzK5GNLhyJGzU8kXRfH6FgsAGyEAlAaMU',
    appId: '1:1059648731028:ios:8a0c8aa50900192ef58181',
    messagingSenderId: '1059648731028',
    projectId: 'new-pyramidion',
    storageBucket: 'new-pyramidion.appspot.com',
    iosClientId: '1059648731028-nf424khecq4ragoe09nbq0iveckt59jm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pyramidionTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzK5GNLhyJGzU8kXRfH6FgsAGyEAlAaMU',
    appId: '1:1059648731028:ios:d255380f6697c60bf58181',
    messagingSenderId: '1059648731028',
    projectId: 'new-pyramidion',
    storageBucket: 'new-pyramidion.appspot.com',
    iosClientId: '1059648731028-k48oijiri4u08015m9p127gs3pbk9hqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.pyramidionTwo.RunnerTests',
  );
}
